### ISSUE TITLE
Sample Errors

### ISSUE THREAD

**Issue by wukeying** [exilon/QuickORM#1]
2 Issues
Sample in \samples\ORMRestServerDemo\source\delphi 
1、 ORMRestServer  AV Error
2、ORMRestClient  Compile Error: Missing  Quick.AppSecurity.pas

**Comment by exilon** [comment]
1. You need sqlite3-64.dll present in your system or in the same directory where .exe will be compiled.
2. Did you add QuickORM source path to delphi library path?
