### ISSUE TITLE
Change in TORMDataBase.SetDBFileName

### ISSUE THREAD

**Issue by juanter** [exilon/QuickORM#2]
Consider this change in code :
`
procedure` TORMDataBase.SetDBFileName(const dbfname : RawUTF8);
begin
  //if dbfile not found, sets as current app dir
  // Modificado Juan
  if (dbfname = SQLITE_MEMORY_DATABASE_NAME) or TFile.Exists(dbfname) then fDBFileName := dbfname
    else fDBFileName := Format('%s\%s',[path.EXEPATH,TPath.GetFileName(dbfname)]);
end;
`

And this to compatibility with custom external databases:
`
function TORMRestServer.Connect(DoCustomDb: TProc): Boolean;
..
if not Assigned(DoCustomDb) then
      case DataBase.DBType of
        dtSQLite:
          begin
            ..
          end;
        dtMSSQL:
          begin
            ..
      end
    else
      DoCustomDb();
  end;
..
end;
`

**Comment by exilon** [comment]
Thanks, i will include your changes in next release.
