### ISSUE TITLE
ORMRestServer->Exception ECrtsocket (SockRecvLn [10060 WSAETimedout... When accesing from web browser to services and methods

### ISSUE THREAD

**Issue by FravemelAutrial** [exilon/QuickORM#4]
First,. thanks again for your effort and awsome work.

Don't khnow if its mormot problem, quickorm or configuration but when I open services or methods whith chrome like http://127.0.0.1:8099/root/ServiceMethods.Sum?[2,2]  i get then following exception:

> First chance exception at $741218E2. Exception class ECrtSocket with message 'SockRecvLn [10060 WSAETIMEDOUT "Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder"]'. Process ORMRestServer.exe (7944)

When I access from ORMRestClient.exe everithing is OK.

I'cant debug it, but found a similar isue at https://synopse.info/forum/viewtopic.php?id=4439

I'm runnint it from delphi 10.3, and I've tried it in Windows 10 in two different computers.

**Comment by FravemelAutrial** [comment]
I've tried to change TSrvProtocol to every option whith the same result except in spHTTPsys* which works ok.
Any Clue?

**Comment by exilon** [comment]
I will check why is raising this error.

**Comment by FravemelAutrial** [comment]
My fault, I realiced that the exception was catched and only shows in debug or vervose_log. (data was returned ok even in the browser)
Maybe is the normal behabiour, just a little weird that only appears when accessing from web browser.
Furthermore it happens in plain mormot.

Thanks again.
