### ISSUE TITLE
Access violation when AuthMode=amNoAuthentication in TORMRestClient.Connect 

### ISSUE THREAD

**Issue by FravemelAutrial** [exilon/QuickORM#5]
if I disable authentification in server and client in TORMRestClient.Connect I get an accces violation in the next line:

```
      //get Auth Group
      fMyAuthGroup := TORMAuthGroup.CreateAndFillPrepare(ORM,'ID=?',[ORM.SessionUser.GroupRights.ID]);
```
Correct me if Im wrong but, I think this should be enclosed in an if  (fHTTPOptions.AuthMode<>amNoAuthentication) then

**Comment by exilon** [comment]
Thanks for your report. Now is fixed.
